version:
  jquery: 3.1.1
  semantic_ui: 2.2.9
  font_awesome: 4.7.0
  moment: 2.17.1
  count_up: 1.8.1
  js_cookie: 2.1.3
  echarts: 3.4.0

google_analytics_id: UA-98271013-1
piwik_analytics_site_id: 1

repository: https://github.com/caiguocn/Jinbu

timezone: Asia/Shanghai

name: 进步英语
author: 步步
author_url: http://www.ejinbu.com
organization: EJinbu
organization_url: http://ejinbu.com
description: 进步英语.读而立·写而生
keywords: 进步听力学英语, 英语, 听力, 四级英语考试, 新概念英语, 六级英语, 托福,雅思,

contact: QQ:4577047

logo: /images/logo.png
logo_dark: /images/logo-dark.png
logo_white: /images/logo-white.png


plugins:
 - jekyll-seo-tag
 - jekyll-sitemap
 # - jekyll-paginate


exclude:
- .gitignore
- .travis.yml
- LICENSE
- README.md
- CNAME
- Gemfile
- Gemfile.lock
- script
- vendor
- less
- node_modules
- Gruntfile.js
- README.md
- front_end
- back_end




# Site settings
title: 进步听力学英语
header-img: "img/green.jpg"
tagline: "cn"
baseurl: ""
url: http://www.ejinbu.com

# About/contact
owner:
  name: " Caiguocn"
  email: caiguocn@qq.com
  bio: "写就是写的报酬"

# Data
gavatar: http://dreamofbook.qiniudn.com/Az..png
favicon: img/favicon.png

douban_username:
twitter_username:
github_username:
facebook_username:
weibo_username:
zhihu_username:


# Build settings
# use Github Flavored Markdown !important
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# Defaults for posts
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "blog_post"
      author: "CnFeat"
      header-img: "img/green.jpg" # We don't want posts without a header image, that whould mean white on white

# Comments
comments :
  provider : duoshuo
  duoshuo :
    short_name :
  disqus :
      short_name :

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation
